# Generated by Django 5.2.7 on 2025-10-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='skills',
        ),
    ]
